# Dependabot configuration for automated dependency updates
version: 2
updates:
  # Python dependencies (using uv package manager)
  # Dependabot will update both pyproject.toml and uv.lock
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    groups:
      python-dev:
        patterns:
          - "pytest*"
          - "mypy"
          - "black"
          - "ruff"
      python-prod:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "mypy"
          - "black"
          - "ruff"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 3
